Information:
  Title: amogusreal69
  Icon: icon.png
  Description: "I love doing stuff that is related to tech. I also do something with softwares and break them. I also manage alot of domains like blueprint.rent, plz-code-for-me.lol, and some others. Want to donate? Donate here: https://ko-fi.com/amogusreal"
  Link: amogusreal69.me
  Theme: CatppuccinMocha

Connections:
  GitHub: amogusreal69
  YouTube:
  Twitter: 
  Mastodon: 
